package app:demo;

interface worker {
    http-fetch: func(url: string) -> result<string, string>;
}

world demo {
    include wasi:cli/imports@0.2.3;
    include wasi:http/imports@0.2.3;
    export worker;
}
